### ISSUE TITLE
`AddSuperUserToIndividualAccounts` doesn't seem to be working

### ISSUE THREAD

**Issue by pradeepgururani** [JonPSmith/AuthPermissions.AspNetCore#109]
We are using v 6.2.0 of library and calling `.AddSuperUserToIndividualAccounts()` to seed Super user.

However it doesn't seem to be working. It does create a user however leaves out creating `AuthP` user and any association with `AccessAll` permission. My conclusion is based on following code from `StartupServiceIndividualAccountsAddSuperUser.cs`:

```
private static async Task CheckAddNewUserAsync(UserManager<TIdentityUser> userManager, string email, string password)
        {
            var user = await userManager.FindByEmailAsync(email);
            if (user != null)
                return;

            user = new TIdentityUser { UserName = email, Email = email };
            var result = await userManager.CreateAsync(user, password);
            if (!result.Succeeded)
            {
                var errorDescriptions = string.Join("\n", result.Errors.Select(x => x.Description));
                throw new InvalidOperationException(
                    $"Tried to add user {email}, but failed. Errors:\n {errorDescriptions}");
            }
        }
```

On database I can see that super user is created in `AspNetUsers` table but not in `AuthUsers`.

Please guide.

**Comment by JonPSmith** [comment]
Hi @pradeepgururani,

There is a section in the AuthP that covers this - see [How to set up a super user when deploying a new application](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/Bulk-Load-admin#how-to-set-up-a-super-user-when-deploying-a-new-application). 

As you will see you need to use both the ASP.NET Core user and the Bulk Load feature.
