### ISSUE TITLE
Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.8.0 directly

### ISSUE THREAD

**Issue by raulidavid** [JonPSmith/AuthPermissions.AspNetCore#112]
NU1107: Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.8.0 directly to project Jiban.Application to resolve this issue. 
 Jiban.Application -> RazorEngineCore 2024.4.1 -> Microsoft.CodeAnalysis.CSharp 4.8.0 -> Microsoft.CodeAnalysis.Common (= 4.8.0) 
 Jiban.Application -> Jiban.Infrastructure -> AuthPermissions.AspNetCore 8.0.0 -> Microsoft.EntityFrameworkCore.Tools 8.0.2 -> Microsoft.EntityFrameworkCore.Design 8.0.2 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0).

**Comment by raulidavid** [comment]
Please @JonPSmith review this issue

**Comment by JonPSmith** [comment]
Hi @raulidavid,

Are you using the latest version, AuthP version 8.0.0, which I released yesterday or an older version. The older version supported .NET 6, 7 and 8 and had some problems with Microsoft.CodeAnalysis... . Version 8.0.0 only supports .NET 8 and should be better, but maybe I missed something.

Let me know.

**Comment by raulidavid** [comment]
I am using the latest AuthP version 8.0.0

**Comment by JonPSmith** [comment]
Hi @raulidavid,

Can I close this issue? It would useful if you could add a comment saying which approach works for you. That would other users if they have the same type of problem.

**Comment by raulidavid** [comment]
I am using the latest version of authp v8.0.0 but I am inheriting from legacy authp classes, I am going to validate it
