### ISSUE TITLE
PLEASE ADD TENANT INACTIVE PROPERTY

### ISSUE THREAD

**Issue by raulidavid** [JonPSmith/AuthPermissions.AspNetCore#114]
I wish add property for tenant disable, I am run Authp 8.0.0

Example [authp].[Tenants]

 [TenantId]
      ,[ParentDataKey]
      ,[TenantFullName]
      ,[IsHierarchical]
      ,[ParentTenantId]
      ,[ConcurrencyToken]
      ,[DatabaseInfoName]
      ,[IsActive]
      ,[HasOwnDb]

**Comment by JonPSmith** [comment]
Hi @raulidavid,

You could create a tenant disable feature by using the AuthP's Down for maintenance's "Manual, tenant database down" feature (see [this diagram](https://www.thereformedprogrammer.net/wp-content/uploads/2022/09/DownForMaintenance-flow.png) in the article) to disable an individual tenant. 

You can find more about the "Down for maintenance" feature in [AuthP's doc](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/%22Down-for-maintenance%22-feature) or [this article](https://www.thereformedprogrammer.net/how-to-take-an-asp-net-core-web-site-down-for-maintenance/).
