### ISSUE TITLE
Improvement to the multi-tenant ITenantChangeService to better support sharding

### ISSUE THREAD

**Issue by JonPSmith** [JonPSmith/AuthPermissions.AspNetCore#14]
An application using AuthP's multi-tenant feature requires a service that implements the `ITenantChangeService` which is called when a tenant is created, updated, moved or deleted. The current implementation creates a transaction that covers both the AuthP DbContext and the application's DbContext.

This works, but has the following limitations:

- The AuthP DbContext and the application's DbContext must use the same database. This rules out the [sharding](https://docs.microsoft.com/en-us/azure/azure-sql/database/saas-tenancy-app-design-patterns#g-multi-tenant-app-with-sharded-multi-tenant-databases) approach to building multi-tenant applications.
- The `ITenantChangeService` is quite complex for the user - it would be nice to make it simpler. One approach would have an abstract class containing a default creation of the application's DbContext, with a way to override that default creation of the DbContext if the developer needs to add extra features.

## Possible solution

Looking at the code it could be changed to a transaction on just the AuthP DbContext, and within that transaction a call to the  (modified) `ITenantChangeService`.  If the ChangeService fails / returns an error it can roll back the AuthP changes.

For some changes, like delete and move, the `ITenantChangeService` would need a transaction too. In this case it gets complex.

## Things to look at 

- [Using external DbTransactions](https://docs.microsoft.com/en-us/ef/core/saving/transactions#using-external-dbtransactions-relational-databases-only)
- [Using System.Transactions](https://docs.microsoft.com/en-us/ef/core/saving/transactions#using-systemtransactions)

**Comment by FELS-Zak** [comment]
Agree :-)  Just found this project - Does it have to use SQL server ?

**Comment by JonPSmith** [comment]
Have a look at the [Roadmap discussions](https://github.com/JonPSmith/AuthPermissions.AspNetCore/discussions/2) for a roadmap of what I'm planning to do - that includes supporting PostgreSQL, but no other database types.

**Comment by JonPSmith** [comment]
PS. @FELS-Zak, why were you interested with this feature?

- You want to use sharding in a multi-tenant app.
- You want a simpler way to handle tenants on your application side.
- You were just interested in this library.

**Comment by JonPSmith** [comment]
In AuthP versions before version 3 the aim was to get all the multi-tenant data within one database. In this case AuthP used a [external DbTransactions](https://docs.microsoft.com/en-us/ef/core/saving/transactions#using-external-dbtransactions-relational-databases-only) approach. This provides one transaction that covers two DbContexts at the same time, but the code is rather complex as couldn't get an instance of the tenant's database DbContext via DI, but you needed to add extra code to manually create the tenant's database DbContext

With the addition in version 3 of the AuthP library of [database sharding](https://docs.microsoft.com/en-us/azure/azure-sql/database/saas-tenancy-app-design-patterns#d-multi-tenant-app-with-database-per-tenant) I decided to simplify the transaction into two separate transactions, with the second transaction run started from within the first transaction. This means that both transactions have to be successful for the database to be updated.

This does mean that the [`ITenantChangeService`](https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/main/AuthPermissions/AdminCode/ITenantChangeService.cs) has changed a lot. Please see the [Update To Version 3](https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/main/UpdateToVersion3.md) file for how update your version 2 code to version 3.

**Comment by akema-trebla** [comment]
[this](https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/main/UpdateToVersion3.md) seems to be broken

**Comment by akema-trebla** [comment]
> Have a look at the [Roadmap discussions](https://github.com/JonPSmith/AuthPermissions.AspNetCore/discussions/2) for a roadmap of what I'm planning to do - that includes supporting PostgreSQL, but no other database types.

Is there a reason you're not considering other database types like MySQL, Oracle?

**Comment by JonPSmith** [comment]
Hi @akema-trebla,

> [this](https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/main/UpdateToVersion3.md) seems to be broken

Yep, that won't be out until version 3.

> Is there a reason you're not considering other database types like MySQL, Oracle?

This library is _really_ complex and is taking a lot of work, which I do for free. The more database types a support requires extra work, but the real reason I want to support lots of databases is the yearly update to the library to the changes in EF Core for each database type.

**Comment by JonPSmith** [comment]
Implemented in version 3
