### ISSUE TITLE
Using with identityuser type int

### ISSUE THREAD

**Issue by Kiwiz777** [JonPSmith/AuthPermissions.AspNetCore#21]
hi there 
i am trying to use IndividualAccountsAuthentication<TCustomIdentityUser>
which in my case class named AppUser inheriting from identity user
`class AppUser : IdentityUser<int>`
and i get an error 
/*
Error	CS0311	The type 'RivaWeb.Models.AppUser' cannot be used as type parameter 'TCustomIdentityUser' in the generic type or method 'SetupExtensions.IndividualAccountsAuthentication<TCustomIdentityUser>(AuthSetupData)'. There is no implicit reference conversion from 'RivaWeb.Models.AppUser' to 'Microsoft.AspNetCore.Identity.IdentityUser'
*/
is there something i am missing or there is no way i can use an int for the user id with this library.

**Comment by JonPSmith** [comment]
Hi @Kiwiz777 

This library relies on a userId that is a string, so you can't have a `IdentityUser<int>`. Sorry, but that is limitation of the library
