### ISSUE TITLE
Guide request for MultiTenancy and Permissions using IdentityServer4

### ISSUE THREAD

**Issue by eslamo** [JonPSmith/AuthPermissions.AspNetCore#33]
Thank you for your great library.

I hope you can share an example how I can use this library to have multi tenant api integrated with IdentityServer4

**Comment by JonPSmith** [comment]
Hi @eslamo,

You can use IdentityServer with AuthP as it implements the [OpenId](https://www.thereformedprogrammer.net/advanced-techniques-around-asp-net-core-users-and-their-claims/#1b-openid-connect) connection. But IdentityServer is designed to provides its own authentication data (known as _Scopes_), but the AuthP library uses its own authentication data known as [Roles](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/Roles-explained) and [Permissions](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/Permissions-explained). Therefore you need to think about who is in charge of authentication: IdentityServer or AuthP.

You _can_ use IdentityServer's Scopes, and ignore AuthP Roles/Permissions, but that removes the possibility of [versioning your multi-tenant app](https://www.thereformedprogrammer.net/multi-tenant-apps-with-different-versions-can-increase-your-profits/). Therefore I would recommend using Azure AD B2C as better authorization handler (see example 5). 

If you still want to use IdentityServer, then you can use the OpenID event to add the AuthP claims, or if you are using a JWT Bearer Token you can inject AuthP claims there (see example 2)

**Comment by eslamo** [comment]
Thanks @JonPSmith for your great explination and details and I hope I can find better solution to connect multiple apps using OpenID and keep using AuthP cause I like the versioning feature and Permission based authentication cause it give more felexibility to the app.
