### ISSUE TITLE
Adding CancellationToken support to async methods

### ISSUE THREAD

**Issue by emorell96** [JonPSmith/AuthPermissions.AspNetCore#44]
Hi,

I think it would be great if the library had CancellationToken support. After all, EF Core supports this already. It would just be a matter of forwarding the cancellation token to EF Core.

**Comment by JonPSmith** [comment]
Developer shouldn't use the `AuthPermissionsDbContext` at all, but use the [Roles](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/Roles-admin-service), [Tenant](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/Single-level-Multi-Tenant) and [AuthUser](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/AuthUser-admin-service) services. Also, cancelling a  CancellationToken in EF Core throws an exception, which isn't a nice outcome - I try to return human-friendly errors.

For those reasons I don't think adding CancellationToken support is worth it.

**Comment by emorell96** [comment]
I meant adding CancellationToken support for the admin services. 

For the exception, the exception is a TaskCancelled exception which is the default exception when an exception is cancelled. This is a developer issue not a user issue if a Task is cancelled. So IMO it shouldn't be an IStatusGeneric but an exception that the developer can easily catch and decide what to do.

**Comment by emorell96** [comment]
For example methods like this: https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/ab4d37f30500707ea9d618b1927cabc305173ce2/AuthPermissions/AdminCode/IAuthUsersAdminService.cs#L29

They could benefit from a CancellationToken so that if a developer uses this, he can decide to cancel the operation after x seconds or simply when the data is no longer needed. And it shouldn't be a IStatusGeneric because then how do you simply catch when the operation is cancelled? With the exception is just a `try{} catch(TaskCancelled ex) {}` code block, and the developer has the choice of what to do. Either log it, or display an error or whatever. But with the StatusGeneric it's nice for when it's a problem shown to the user directly as you say on the wiki but it has a few downsides like not been able to localize the error messages if displayed to users, or doing all the things you'd do with a simple try catch block are now more difficult.

**Comment by JonPSmith** [comment]
Hi @emorell96,

I have thought about this and I just don't think its worth it. All the methods access a normal database, not some microservice or HTTP api. Sorry.

If you want to do it then please have your own clone.

**Comment by emorell96** [comment]
Why would this only apply to an http api or a microservice? There's a reason the EF Core team uses cancelation tokens, it avoids having to waste database resources when the data is no longer needed, say the user navigates away before loading the data. This is a backend library and these features are c# features and best practices which allow the library to be used in high load scenarios as well.

I do not understand the reticence specially since it isn't a breaking change and something that I'd be happy to contribute even after you are done with the dev branch to make sure I do not work against what you are doing.

I will still have my own clone but it feels like a shame to have the code diverge on simple things like this :/

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
