### ISSUE TITLE
Question about the design

### ISSUE THREAD

**Issue by idan-h** [JonPSmith/AuthPermissions.AspNetCore#46]
Hey, I have a question;
Why not extend microsoft's identity framework, instead of managing multiple tables in parallel?

(Ex. dbo.AspNetUsers - authp.AuthUsers)

You can use a custom user, add the roles etc, all in the same context, and then add the tenants and required extra tables and services

It makes the need of sync between those tables unnecessary, and the db much more normalized and less complex.

Great work btw,
Thanks!

**Comment by idan-h** [comment]
I think it clicked with me, Is it so that if you would want to move to another authentication provider it would be easier?

**Comment by JonPSmith** [comment]
Yep, you are right. The Azure AD is a great authentication provider and I wanted to support. I also don't think you can alter microsoft's identity framework to cover all the things that the AuthP needs.
