### ISSUE TITLE
Code for minimal API's fluent HasPermission

### ISSUE THREAD

**Issue by idan-h** [JonPSmith/AuthPermissions.AspNetCore#49]
Hey, I wrote small piece of code to handle the `HasPermission` attribute fluently for minimal api.

Usage:
```
app.MapGet("/", () => "Hello World!")
            .HasPermission(ApplicationPermission.AccessAll);
```

Extension method:
```
public static TBuilder HasPermission<TBuilder>(this TBuilder builder, object permission) where TBuilder : IEndpointConventionBuilder
  {
      var authorizeData = new HasPermissionAttribute(permission);
      builder.RequireAuthorization(authorizeData);

      return builder;
  }
```

Which namespace you would like this method to go into? I think people who use minimal api might find it useful

**Comment by JonPSmith** [comment]
Yes, that would be useful.

You should add the method into the [PermissionChecks](https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/main/AuthPermissions.BaseCode/PermissionsCode/PermissionChecks.cs) static class and add a test(s) in the [TestPermissionChecker](https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/main/Test/UnitTests/TestAuthPermissions/TestPermissionChecker.cs).

**Comment by idan-h** [comment]
@JonPSmith Tried adding to that class, but couldn't because it depends on asp.net core.
Added in 
`Test.UnitTests.TestAuthPermissionsAspNetCore.TestPermissionPolicy`
and
`AuthPermissions.AspNetCore.PolicyCode.PermissionExtensions`
instead

**Comment by JonPSmith** [comment]
Hi @idan-h,

Yes, that was the correct thing to add it to the `AuthPermissions.AspNetCore.PolicyCode` namespace. I'm not planning a release straight away as I have a few other things to do.
