### ISSUE TITLE
Create a demo using JWT and Cookie both

### ISSUE THREAD

**Issue by MahmudX** [JonPSmith/AuthPermissions.AspNetCore#64]
I haven't found any **good** tutorial that demonstrate how to use both JWT and Cookie based authentication in a standard way.

A demo project with detailed article would be great.

**Comment by JonPSmith** [comment]
Hi @MahmudX,

There are two ways to read your question:

#### Authentication using BOTH JWT and Cookie authentication

This is very rare you need both, but Rick Strahl has [this article](https://weblog.west-wind.com/posts/2022/Mar/29/Combining-Bearer-Token-and-Cookie-Auth-in-ASPNET)

#### Good tutorials of either JWT or Cookie authentication

There are loads of good tutorials on this. Here are two

- [Cookie authentication](https://www.c-sharpcorner.com/article/cookie-authentication-in-asp-net-core/)
- [JWT authentication](https://www.c-sharpcorner.com/article/jwt-json-web-token-authentication-in-asp-net-core/)
