### ISSUE TITLE
Invite user that already invited on another tenant by same email Id.

### ISSUE THREAD

**Issue by imprathamesh** [JonPSmith/AuthPermissions.AspNetCore#71]
Hi Jon,
I want to know that is it possible to do same email id can be user of another tenant. 
Like some application, I seen, Admin of App can invite user which is already somewhere invited or Tenant. 

In AuthPermission Project, When I am trying to add it will not allow because email Id already present in AspNetUsers table. 

Any suggestion on this, sir?

**Comment by JonPSmith** [comment]
Hi @imprathamesh,

There is a limitation to this library that a user can only be linked to one user. Other developers have asked this and I explain the problem in issue #68 if you want to read it.
