### ISSUE TITLE
AddSingleTenantReadWriteQueryFilter for Entity type hierarchy

### ISSUE THREAD

**Issue by stevenoglesby** [JonPSmith/AuthPermissions.AspNetCore#74]
For an entity type hierarchy (using the default setup of TPH) checking for assignability to IDataKeyFilterReadWrite and using AddSingleTenantReadWriteQueryFilter to set up the query filter does not work.

All entities in the hierarchy share a single table in the DB and AddSingleTenantReadWriteQueryFilter will try to setup an (unnamed) index on the table for each entity in the hierarchy.

I think that the query filter needs setting on each entity in the hierarchy.
However, the DataKey property tweaks and the index only need adding to the table once at top level entity that has the property.

For TPT and TPC models it is quite probably different.

Happy to have a look at implementing.
Wanted to get any thoughts you had / check it wasn't already being worked on first.

Steven

**Comment by JonPSmith** [comment]
Hi @stevenoglesby,

OK I can see what you are talking about and assume you tried this and found there is a problem (I haven't tried it myself). The `AddSingleTenantReadWriteQueryFilter` is provided to help developers, but it isn't linked to the AuthP code so you can replace it if your database has some more complex setup.

When it comes to TPT and TPC I think provided `AddSingleTenantReadWriteQueryFilter` would work as these have their own tables (but I haven't tried it).

PS. If you haven't tried TPH with the provided `AddSingleTenantReadWriteQueryFilter` code then its worth a look. I wonder whether EF Core knows they all have the same database and only add one index, or SQL Server maybe ignore the extra indexes because they have the same name.

**Comment by stevenoglesby** [comment]
Hi @JonPSmith,

Yes, I have TPH set up and when calling `AddSingleTenantReadWriteQueryFilter` on all the entity types in the hierarchy hit an exception:
The index {'DataKey'} cannot be added to the entity type 'XXXX' because an unnamed index on the same properties already exists on entity type 'YYYY'. Consider adding a name for one of the indexes in 'OnModelCreating'.

I haven't tried TPT or TPC yet.

For a hierarchy:
Abstract EntityA (extends IDataKeyFilterReadWrite) - with Id, PropA, DataKey
EntityB (extends EntityA) - with PropB
EntityC (extends EntityA) - with PropC

From the docs (https://learn.microsoft.com/en-us/ef/core/modeling/inheritance) my understanding is...

For TPH we would have a single table:
TableA with columns:
Id, Discriminator, PropA, DataKey, PropB, PropC

So in this case we need to:
- add Index to TableA
- add query filter to EntityA, EntityB and EntityC

For TPT we would have 3 tables:
TableA with columns:
Id, PropA
TableB with columns:
Id (FK to TableA Id), PropB
TableC with columns:
Id (FK to TableA Id), PropC

N.B. Any query run will always do an INNER JOIN to TableA.
So in this case we need to:
- add Index to TableA
- add query filter to EntityA, EntityB and EntityC

For TPC we would have 2 tables:
TableB with columns:
Id, DataKey, PropA, PropB
TableC with columns:
Id, DataKey, PropA, PropC

N.B. A query for EntityA would perform queries for EntityB and EntityC and then UNION ALL the results
So in this case we need to:
- add Index to TableB and TableC
- add query filter to EntityB and EntityC
- Not sure if we need to add query filter to EntityA - I think this would happen on the individual queries before the UNION ALL happens?

> The AddSingleTenantReadWriteQueryFilter is provided to help developers, but it isn't linked to the AuthP code so you can replace it if your database has some more complex setup.

As this probably falls under 'more complex setup' perhaps the best way to handle this is to add some documentation to the wiki?

**Comment by JonPSmith** [comment]
Hi @stevenoglesby,

Thanks for that. That is very helpful and I added a update to the [database article here](https://www.thereformedprogrammer.net/building-asp-net-core-and-ef-core-multi-tenant-apps-part1-the-database/#update-jan-2023) (the `AddSingleTenantReadWriteQueryFilter` isn't talked about in the AuthP's documentation).

Once you have checked out your code to replace the `AddSingleTenantReadWriteQueryFilter` extension method could you add your final solution to this issue to help others that come across this issue.

**Comment by stevenoglesby** [comment]
Quick update:

For TPH based inheritance I have found that you just need to call AddSingleTenantReadWriteQueryFilter on the base entity in the hierarchy (and should not call it on sub-entities in the hierarchy).

**Comment by ccnicholls99** [comment]
Bumped into the same issue and found this is working for me (so far)...


In your DBContext.OnModelCreating(ModelBuilder modelBuilder) method...add this, or some variation of it...
```c#
foreach (var entityType in modelBuilder.Model.GetEntityTypes())
{
  if (typeof(IDataKeyFilterReadWrite).IsAssignableFrom(entityType.ClrType))
  {
      // AddSingleTenantReadWriteQueryFilterdoes not work for TPH sub-entities. 
      // If you try, you will get the following during migration...
      //      The index {'DataKey'} cannot be added to the entity type 'XXXX' because
      //      an unnamed index on the same properties already exists on entity type 'YYYY'.
      //      Consider adding a name for one of the indexes in 'OnModelCreating'.
      // Ignore this call for all entitytypes with a Base Type, assuming the base type implements IDataKeyFilter[...]
      if (entityType.BaseType == null)
      {
          entityType.AddSingleTenantReadWriteQueryFilter(this);
      }
    }
    else
    {...omitted for brevity...}
``` 

NOTE: I haven't fully tested this out yet but it got me past migration.

**Comment by JonPSmith** [comment]
I haven't heard about this for some time so I am closing this.
