### ISSUE TITLE
Some claim changes ignored until logout/login

### ISSUE THREAD

**Issue by TheObliterator** [JonPSmith/AuthPermissions.AspNetCore#87]
I've implemented the RoleChangedDetectorService and if I change the roles assigned to a user it seems to take immediate effect which is great. However, if I edit the permissions enabled in a role this doesn't seem to trigger an update to logged-in users claims.
It seems to identify users that will be impacted (i.e. users belonging to that role) but it doesn't actually cause their claims to be updated (until the user logs out and back in). Am I missing something?

Additionally, if I edit the tenant a user belongs to, the user's data key in their claim does not get updated (until logout/login).
Is this by design? The TenantKeyOrShardChangeService only looks to detect changes to the Tenant Hierarchy, not changes to an individual user's tenant.

I've implemented the various change services as per your examples, so my understanding is it shouldn't be necessary for the user to logout and log back in again for changes to their account to become effective. Specifically I've implemented: GlobalChangeTimeService, SomethingChangedCookieEvent, RoleChangedDetectorService and TenantKeyOrShardChangeService.

Thanks in advance and apologies if I'm missing something obvious.

**Comment by JonPSmith** [comment]
The RoleChangedDetectorService class detects changes to the permissions, and the users that are are effected by the permissions change, and then caches these changes in a global cache. The other part can be seen in the [UpdateRoleClaimMiddleware](https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/main/Example2.WebApiWithToken.IndividualAccounts/ClaimsChangeCode/UpdateRoleClaimMiddleware.cs) (found in Example2), which updates the Permissions claim. This is approach 2 in the [ASP.NET Core: Three(+1) ways to refresh the claims of a logged-in user](https://www.thereformedprogrammer.net/asp-net-core-three-ways-to-refresh-the-claims-of-a-logged-in-user/) article.

I hope that helps.
