### ISSUE TITLE
Soft Delete 

### ISSUE THREAD

**Issue by bahaAbualkibash** [JonPSmith/AuthPermissions.AspNetCore#98]
Hi there,

I'm currently using this library and looking to implement a soft delete functionality instead of hard delete tenants/users/etc..., and I'm unsure about the best approach to achieve this within the library.

Could you provide guidance or best practices on how to implement soft delete functionality? Any code snippets, recommended practices, or pointers to relevant resources would be immensely helpful.

Thank you in advance for your assistance :)

**Comment by JonPSmith** [comment]
Hi @bahaAbualkibash,

I actually built a library called [`EfCore.SoftDeleteServices`](https://github.com/JonPSmith/EfCore.SoftDeleteServices) which handles soft-delete and a multi-tenant key. [The wiki](https://github.com/JonPSmith/EfCore.SoftDeleteServices/wiki) holds documentation, plus links on the right to two articles and a [EF Core standup](https://www.youtube.com/watch?v=Uy0c_DKGM-U) where talked about soft delete with tenants (about 35 mins in).

Enjoy.
